### ISSUE TITLE
BLS Monthly Employment Situation Report

### ISSUE THREAD

**Issue by mwkaufman** [rearc-data/covid-datasets-aws-data-exchange#17]
A product based on the Bureau of Labor Statistics' Monthly Employment Situation Report released on the first Friday of each month.

**Comment by rahulsen** [comment]
I am looking at this.

**Comment by rahulsen** [comment]
https://github.com/rearc/aws-data-exchange-bls-national-employment - initial documentation

**Comment by mwkaufman** [comment]
National:

https://console.aws.amazon.com/dataexchange/home?region=us-east-1#/products/prodview-zlve3phknot2c

State & Metro:

https://console.aws.amazon.com/dataexchange/home?region=us-east-1#/products/prodview-o2l5bdo54mbju
