### ISSUE TITLE
Coronavirus COVID-19 Cases Data for China and the Rest of the World

### ISSUE THREAD

**Issue by varmamahesh** [rearc-data/covid-datasets-aws-data-exchange#19]
https://data.humdata.org/dataset/coronavirus-covid-19-cases-data-for-china-and-the-rest-of-the-world

**Comment by derekwolpert** [comment]
WHO depreciated this dataset. We have already published the one that replaced it on ADX

https://github.com/rearc-data/who-covid-19-cases-deaths
