### ISSUE TITLE
CDC / NCHS - Provisional Death Counts for Coronavirus Disease (COVID-19): Weekly State-Specific Data Updates

### ISSUE THREAD

**Issue by derekwolpert** [rearc-data/covid-datasets-aws-data-exchange#39]
https://data.cdc.gov/NCHS/Provisional-Death-Counts-for-Coronavirus-Disease-C/pj7m-y5uh

**Comment by milin82** [comment]
sorry @derekwolpert, taking this one from you

**Comment by derekwolpert** [comment]
@milin82 no worries, I knew this was one that would be better to get up ASAP
