### ISSUE TITLE
COVID-19 Data from Robert Koch Institute (RKI)

### ISSUE THREAD

**Issue by mwkaufman** [rearc-data/covid-datasets-aws-data-exchange#68]
COVID-19 Data from Robert Koch Institute (RKI)

https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0

Product description page in German first

**Comment by derekwolpert** [comment]
This product request is completed and is in the process of publishing on ADX.

https://github.com/rearc-data/covid-19-deutschland-robert-koch-institut

READMEs will be adjusted to link to the product once it is live.
