### ISSUE TITLE
OpenTable state of the restaurant industry

### ISSUE THREAD

**Issue by mwkaufman** [rearc-data/covid-datasets-aws-data-exchange#8]
https://www.opentable.com/state-of-industry

Need to review the license.

**Comment by aduyko** [comment]
Currently reaching out to OpenTable to figure out licensing

**Comment by mwkaufman** [comment]
Code roughed out here, but need signoff from OpenTable to proceed due to the license terms we found: https://github.com/rearc/aws-data-exchange-opentable-state-of-industry
