### ISSUE TITLE
Delphi epidemiological data API

### ISSUE THREAD

**Issue by mwkaufman** [rearc-data/covid-datasets-aws-data-exchange#9]
https://github.com/cmu-delphi/delphi-epidata

**Comment by mwkaufman** [comment]
Most of the data in the API is being republished from other sources (e.g. CDC FluView data) although this might be the only place to source ILI Nearby data. Punting at this time due to the complexity and it not being directly COVID-19 data.

**Comment by milin82** [comment]
APIs have been updated to include Delphi’s COVID-19 Surveillance Streams (covidcast). See https://cmu-delphi.github.io/delphi-epidata/api/covidcast
